### ISSUE TITLE
[REPO] Upgrade to Yarn 2 & Plug'n'Play

### ISSUE THREAD

**Issue by inferrinizzard** [inferrinizzard/prettier-sql#43]
Yarn 2 features new Plug'n'Play that deprecates node_modules in favour of .pnp.cjs
Info: https://yarnpkg.com/features/pnp

**Comment by inferrinizzard** [comment]
Placing on hold as typescript and pre-commit hooks still do not work properly with Plug'n'Play

**Comment by iugo** [comment]
Maybe just use npm.

**Comment by inferrinizzard** [comment]
Closing as Yarn PnP will no longer be pursued as a repo tool option
