### ISSUE TITLE
[SCRIPT] Unsupported Regex breaks the app in Safari

### ISSUE THREAD

**Issue by yuliiakorabelska** [inferrinizzard/prettier-sql#84]
**Describe the bug**
Trying to bring up the web app in Safari results in SyntaxError: Invalid regular expression: invalid group specifier name error in Console. Works fine in Chrome.
**To Reproduce**

1. do `npm i prettier-sql` in your project
2. start the project
3. Open the page in Safari
4. View Develop /Web Inspector/Console. Observe:
`SyntaxError: Invalid regular expression: invalid group specifier name
`

**Expected behavior**
App compiles and works fine.

**Additional context**
The regex that seems to be breaking it is` /(?<=[^\s]+) (AS )?(?=[^\s]+,?$)/i` in [Formatter.ts](https://github.com/inferrinizzard/prettier-sql/blob/db8f64c280b67098a5fbe4e0cf7f2c1b04424068/src/core/Formatter.ts#L187)
Per https://caniuse.com/js-regexp-lookbehind, LookBehind is not supported in Safari

**Comment by inferrinizzard** [comment]
Did not consider availability of lookbehind but will see if I can find a workaround for 5.x versions, this issue will definitely be gone in 6.x

**Comment by nene** [comment]
This is now fixed in sql-formatter 6.0.0

**Comment by yuliiakorabelska** [comment]
@nene Thanks!
